#!/usr/bin/python

from twisted.internet import reactor

import txros
from txros import util, action

from uf_common.msg import MoveToAction, MoveToGoal, PoseTwistStamped
from uf_common import orientation_helpers


@util.cancellableInlineCallbacks
def main():
    nh = yield txros.NodeHandle.from_argv('actiontestnode', anonymous=True)

    trajectory = nh.subscribe('trajectory', PoseTwistStamped)
    moveto = action.ActionClient(nh, 'moveto', MoveToAction)
    
    print 'start'
    
    pose = orientation_helpers.PoseEditor.from_PoseTwistStamped(
        (yield trajectory.get_next_message()))
    
    print pose
    
    goal_manager = moveto.send_goal(pose.forward(0.5).as_MoveToGoal())
    
    yield goal_manager.get_result()
util.launch_main(main)
