#!/usr/bin/python

from twisted.internet import reactor

import txros
from txros import util

from geometry_msgs.msg import PointStamped


nh = txros.NodeHandle('testnode')

pub = nh.advertise('point2', PointStamped, latching=True)
def cb(msg):
    pub.publish(msg)
sub = nh.subscribe('point', PointStamped, cb)

@util.inlineCallbacks
def task1():
    msg = yield sub.get_next_message()
    print msg
task1()

@util.inlineCallbacks
def task2():
    while True:
        yield util.sleep(1)
        x = yield nh.get_param('/')
task2()

@util.inlineCallbacks
def task3():
    while True:
        pub = nh.advertise('point3', PointStamped, latching=True)
        for i in xrange(5):
            yield util.sleep(0.1)
            pub.publish(PointStamped())
        yield pub.shutdown()
task3()

reactor.run()
