#!/usr/bin/python

from twisted.internet import reactor

import txros
from txros import util

from geometry_msgs.msg import PointStamped


nh = txros.NodeHandle('testnode')

@repr
@apply
@util.inlineCallbacks
def main():
    pub = yield nh.advertise('point2', PointStamped, latching=True)
    def cb(msg):
        #print msg
        pub.publish(msg)
    sub = yield nh.subscribe('point', PointStamped, cb)
    
    while True:
        msg = yield sub.get_next_message()
        print msg

@repr
@apply
@util.inlineCallbacks
def _():
    while True:
        yield util.sleep(1)
        print (yield nh.get_param('/'))

reactor.run()
