#!/usr/bin/python

import traceback

from twisted.internet import reactor

import genpy

import txros
from txros import util
from txros import tf

nh = txros.NodeHandle.from_argv('test_tf', anonymous=True)

tf_listener = tf.TransformListener(nh)

@util.cancellableInlineCallbacks
def task1():
    while True:
        try:
            time = nh.get_time() - genpy.Duration(1)
            transform = yield tf_listener.get_transform('/parent', '/child', time)
            transform2 = yield tf_listener.get_transform('/parent', '/child', time+genpy.Duration(0, 1000000))
        except Exception:
            traceback.print_exc()
        else:
            print time
            print transform
            print (transform2 - transform)/1e-3
            print
        yield util.sleep(0.01)
task1()

reactor.run()
